// Generated by Wrangler by running `wrangler types`

interface Env {
	GITHUB_API_URL: "https://api.github.com";
	REPO_NAME: "23people-handbook";
	REPO_OWNER: "23people-io";
	VECTOR_STORE_WORKER_BASE_URL: "https://23people-handbook-vector-store.cloudflare-23people-io-account.workers.dev";
	VECTOR_STORE_WORKER_ENDPOINT: "api/vectors";
	GITHUB_API_TOKEN: string;
	HANDBOOK_INDEX: VectorizeIndex;
	AI: Ai;
}
