# Markdownlint configuration with all properties set to their default value

# Default state for all rules
default: true

# Path to configuration file to extend
extends: null

# Individual rule configurations
no-hard-tabs: false
MD013: false
MD033: false
MD042: false
MD046: false
MD051: false
MD007:
  indent: 4
MD036: false
MD041: false
MD040: false
MD024: false
MD060: false