// Generated by Wrangler by running `wrangler types`

interface Env {
	OPENAI_EMBEDDINGS_MODEL: "text-embedding-3-small";
	OPENAI_EMBEDDINGS_DIMENSIONS: 768;
	OPENAI_EMBEDDINGS_API_ENDPOINT: "https://api.openai.com/v1/embeddings";
	REPO_NAME: "23p-handbook";
	REPO_OWNER: "23people-io";
	HANDBOOK_VECTORIZE_INDEX_ID: VectorizeIndex;
	AI: Ai;
}
