#!/bin/sh

# script/update: Update application to run for its current checkout. It is used to update the project after a fresh pull.

set -e

cd "$(dirname "$0")/.."

# ANSI color codes
MAGENT=$(tput -Txterm setaf 5)
GREEN=$(tput -Txterm setaf 2)
YELLOW=$(tput -Txterm setaf 3)
WHITE=$(tput -Txterm setaf 7)
RED=$(tput -Txterm setaf 1)
BLUE=$(tput -Txterm setaf 6)
RESET=$(tput -Txterm sgr0)

echo "${MAGENT}Starting update...${RESET}"

script/bootstrap

echo "${MAGENT}✔ Update completed successfully.${RESET}"