#!/bin/sh

# script/version: Version the application for a tag.

set -e

cd "$(dirname "$0")/.."

# ANSI color codes
MAGENT=$(tput -Txterm setaf 5)
GREEN=$(tput -Txterm setaf 2)
YELLOW=$(tput -Txterm setaf 3)
WHITE=$(tput -Txterm setaf 7)
RED=$(tput -Txterm setaf 1)
BLUE=$(tput -Txterm setaf 6)
RESET=$(tput -Txterm sgr0)

if [ -z "${t}" ]; then
    echo "${RED}Error: The Tag version: 't' is required.${RESET}"
    echo "${YELLOW}Usage:${RESET} make version t=[patch/minor/major] m=\"Message\"${RESET}"
    echo "${YELLOW}Options:${RESET}"
    echo "${YELLOW}  t=patch:${RESET}   Increment the patch version${RESET}"
    echo "${YELLOW}  t=minor:${RESET}   Increment the minor version${RESET}"
    echo "${YELLOW}  t=major:${RESET}   Increment the major version${RESET}"
    echo "${YELLOW}  m=\"Message\":${RESET}  Optional commit message${RESET}"
    exit 1
fi

echo "${YELLOW}Linting...${RESET}"
scripts/lint

echo "${YELLOW}Testing...${RESET}"
# script/test

echo "${YELLOW}Making version...${RESET}"
poetry version "${t}"
poetry version
git add .
git commit -m "$(poetry version -s): ${m:-}"
git tag "$(poetry version -s)"
git push
git push --tags
poetry version

echo "${GREEN}✔ Git Tag Version created successfully...${RESET}"